# CodeRabbit Configuration
# Docs: https://docs.coderabbit.ai/configuration

reviews:
  # Show all issues - bugs, style, improvements, everything
  high_level_summary: true

  # Keep reviews thorough
  poem: false

chat:
  auto_reply: true
